[REVIEW] ENH Add dask-cuda docs
rapidsai/docs pull request #193
Opened 2021-05-13 17:07 UTC by dillon-cullinan

Adds dask-cuda docs to the RAPIDS docs site.

2021-05-17 13:33 UTC, charlesbluca requested changes
Thanks @dillon-cullinan! I'll include @rapidsai/daskcuda-python-codeowners for viz; not sure if there are any thoughts on what the blurb should say

2021-05-17 13:33 UTC, charlesbluca commented on _data/docs.yml
> +  cucim:
```suggestion
  dask-cuda:
```

2021-05-17 16:10 UTC, dillon-cullinan commented
Ya I just copied it from the top of the Dask CUDA README, figured that would be fine.

2021-05-17 18:08 UTC, charlesbluca approved these changes
Thanks again @dillon-cullinan!

2021-05-19 17:19 UTC, ajschmidt8 approved these changes

2021-05-19 17:19 UTC, merged