[REVIEW] Update CUDA 11.4 rsn
rapidsai/docs pull request #214
Opened 2021-07-27 16:30 UTC by Salonijain27

Updated RSN 10 to mention CUDA 11.4 is experimental

2021-07-27 16:31 UTC, Salonijain27 commented
@raydouglass please can I get a review for the PR

2021-07-28 14:58 UTC, raydouglass requested changes
Please update the `notice_updated` field to be the current date.

2021-07-28 17:06 UTC, Salonijain27 commented
Updated the PR to change `notice_updated` date to reflect today's date

2021-07-28 17:18 UTC, raydouglass approved these changes

2021-07-28 17:18 UTC, merged