[REVIEW] Notice for 21.08 hotfix
rapidsai/docs pull request #219
Opened 2021-08-09 22:29 UTC by Salonijain27

Two new notices added for:
- `cudf` and `cucim` hotfix to v21.08.01
- `cudf` (v21.08.02), `rmm`, `cuml`, `cugraph`, and `cuspatial` (v21.08.01)

2021-08-09 22:30 UTC, Salonijain27 commented
@raydouglass and @fondaing  Please can I get a review for this PR

2021-08-09 22:57 UTC, fondaing reviewed
#84 - not sure if you want (#84) of if you wanted to take all the parenthesis off the links.  (#8984) (#8968)

you don't have for #56

2021-08-11 21:09 UTC, fondaing approved these changes
LGTM

2021-08-12 16:38 UTC, ajschmidt8 approved these changes

2021-08-12 17:01 UTC, raydouglass requested changes

2021-08-12 17:01 UTC, raydouglass commented on _notices/rgn0017.md
> +title: "Hotfix release for five libraries"
Maybe `Hotfix 21.08 release for five libraries"

2021-08-12 17:23 UTC, raydouglass approved these changes

2021-08-12 17:23 UTC, merged