cudadeprecation 14&15
rapidsai/docs pull request #326
Opened 2023-01-27 17:51 UTC by caryr35

CUDA 14 and 15 Deprecation notices

2023-02-22 23:12 UTC, exactlyallan commented
@caryr35 can this be closed?

2023-03-08 18:49 UTC, aravenel requested changes

2023-03-08 18:49 UTC, aravenel commented on _notices/rsn0027.md
> +notice_created: 2023-01-27
```suggestion
notice_created: 2023-03-08
```

2023-03-08 18:49 UTC, aravenel commented on _notices/rsn0027.md
> +notice_updated: 2023-01-27
```suggestion
notice_updated: 2023-03-08
```

2023-03-08 18:49 UTC, aravenel commented on _notices/rsn0027.md
> +RAPIDS is deprecating `CUDA 11.4` and `CUDA 11.5` containers in its upcoming `v23.02` release. RAPIDS will plan to EOL these containers in a future release (currently targeting `v23.04`), at which po
```suggestion
RAPIDS is deprecating `CUDA 11.4` and `CUDA 11.5` containers effective its `v23.04` release. RAPIDS will plan to EOL these containers in a future release (currently targeting `v23.06`), at which point `CUDA 11.4` and `CUDA 11.5` containers will no longer be published.
```

2023-03-08 18:49 UTC, aravenel commented on _notices/rsn0027.md
> +Once these containers reach EOL (currently targeting `v23.04` release), RAPIDS will no longer publish these containers. Conda packages will still support `CUDA 11.4` and `CUDA 11.5` due to CUDA Enhan
```suggestion
Once these containers reach EOL (currently targeting `v23.06` release), RAPIDS will no longer publish these containers. Note that conda packages will still support `CUDA 11.4` and `CUDA 11.5` due to CUDA Enhanced Compatibility.
```

2023-03-08 18:49 UTC, aravenel commented on _notices/rsn0027.md
> +notice_rapids_version: "v23.02+"
```suggestion
notice_rapids_version: "v23.04+"
```

2023-03-08 19:02 UTC, merged