Release Process Updates
rapidsai/docs pull request #468
Opened 2024-01-19 21:42 UTC by caryr35

This PR is add  item 'Final call for new release artifacts in PIC synch' to the Release Burndown process

2024-01-19 22:04 UTC, raydouglass commented on releases/process.md
> +For the selection of a `burn down date`, the genereral guidelines should be followed:
```suggestion
For the selection of a `burn down date`, the general guidelines should be followed:
```

2024-01-22 16:26 UTC, aravenel requested changes

2024-01-22 16:26 UTC, aravenel commented on releases/process.md
> +1. Final call for new release artifacts in PIC synch (2 weeks prior to cuDF burndown)
```suggestion
1. Inform operations team of any new release artifacts (packages, wheels, containers) no later than 2 weeks prior to cuDF burndown.
```

2024-01-22 16:26 UTC, aravenel commented on releases/process.md
> +1. Final call for new release artifacts in PIC synch (2 weeks prior to cuDF burndown)
Didnt want to mention PIC sync as these docs are public and PIC syncs are internal NV-only.

2024-02-27 13:58 UTC, bdice commented on releases/process.md
> +1. Inform operations team of any new release artifacts (packages, wheels, containers) no later than 2 weeks prior to cuDF burndown.
Small edit: remove trailing period to align with the other items in this list.
```suggestion
1. Inform operations team of any new release artifacts (packages, wheels, containers) no later than 2 weeks prior to cuDF burndown
```

2024-02-27 13:59 UTC, bdice approved these changes
This looks fine to me. @aravenel Can you review this? You requested changes so I want to be sure you're on board before merging. (Just doing a bit of cleanup of PRs in this repo so I came across it again)

2024-02-27 16:36 UTC, aravenel approved these changes
LGTM. Thanks @bdice!

2024-02-27 16:36 UTC, merged