Remove librmm docs
rapidsai/docs pull request #517
Opened 2024-06-07 18:04 UTC by raydouglass

`librmm` docs were merged into `rmm` docs and `24.02` was the last version to have separated `librmm` docs.

Now that the legacy version is `24.04`, the `librmm` docs can be removed.

Ref: https://github.com/rapidsai/docs/pull/478
https://github.com/rapidsai/docs/actions/runs/9421083274/job/25954311807

2024-06-07 18:09 UTC, bdice requested changes
We need a solution for libcudf's docs that currently depend on librmm's Doxygen docs.

See https://github.com/rapidsai/cudf/blob/39c5b86645dc61bf0c59d7bf733ca13872b46a44/cpp/doxygen/Doxyfile#L2229

2024-06-07 18:09 UTC, ajschmidt8 approved these changes

2024-06-07 18:59 UTC, raydouglass commented
> We need a solution for libcudf's docs that currently depend on librmm's Doxygen docs.

After some internal discussions, this does need to be addressed, but we don't want to block updating to the `24.06` docs, so going to override and merge this PR.

2024-06-07 18:59 UTC, merged

2024-07-10 17:08 UTC, bdice commented
Following up: https://github.com/rapidsai/rmm/pull/1604 re-adds librmm docs. From discussion with @raydouglass, we don't need to link to them publicly on docs.rapids.ai, as they are already included in the rmm docs (both C++ and Python). The librmm docs will just be used to cross-reference from libcudf docs.