Dropping Support for Python v3.9 and adding Python 3.12 Support in Release v24.10"
rapidsai/docs pull request #528
Opened 2024-08-06 21:22 UTC by caryr35

This PR is Dropping Support for Python v3.9 and adding Python 3.12 Support in Release v24.10

2024-08-06 22:02 UTC, bdice approved these changes

2024-08-07 04:35 UTC, jakirkham approved these changes

2024-08-07 04:36 UTC, jakirkham commented
cc @jameslamb @mmccarty (for awareness)

2024-08-07 16:11 UTC, jameslamb approved these changes
🤝

2024-08-07 19:38 UTC, jakirkham commented
Based on offline discussion, we are going to wait a day or so for feedback

Deferring to Alex on when it makes sense to merge

2024-08-09 17:37 UTC, aravenel requested changes

2024-08-09 17:37 UTC, aravenel commented on _notices/rsn0040.md
> +notice_pin: false # set to true to pin to notice page
```suggestion
notice_pin: true # set to true to pin to notice page

```

2024-08-09 17:37 UTC, aravenel approved these changes

2024-08-09 17:39 UTC, merged